services:
  db:
    image: postgres:16-alpine
    container_name: store_db
    restart: always
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d store_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M

  backend:
    image: xromza/hekr-store-backend:latest
    container_name: store-backend
    restart: always
    expose:
      - "8080"
    depends_on:
      db-dev:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/store_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
      - JAVA_OPTS=-Xmx768m -XX:ActiveProcessorCount=2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  frontend:
    image: xromza/hekr-store-nextjs:latest
    container_name: store-nextjs
    restart: always
    expose:
      - "3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=/api 
      - BACKEND_URL=http://backend:8080/api
    deploy:
      resources:
        limits:
          memory: 512M


volumes:
  postgres_data:
networks:
  default:
    external: true
    name: shop-network