import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Begin from "@/components/Begin";
import Footer from "@/components/Footer";
import "./globals.css";

const openSans= Open_Sans({
  weight:"400",
  subsets:["cyrillic", "latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${openSans.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"><Begin/>{children}
      <Footer/></body>
    </html>
  );
}
