GRANT ALL ON SCHEMA public TO public;

-- =============================================================================
-- 1. СПРАВОЧНИКИ
-- =============================================================================

CREATE TABLE public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64) UNIQUE NOT NULL
);

CREATE TABLE public.warehouses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address text NOT NULL
);

CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(32) UNIQUE NOT NULL,
    password_hash text NOT NULL,
    role varchar(32) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_approved boolean NOT NULL DEFAULT false,
    client_type varchar(32) NOT NULL,
    phone varchar(20) NOT NULL,
    email varchar(256) NOT NULL
);

-- =============================================================================
-- 2. ТОВАРЫ И ЦЕНООБРАЗОВАНИЕ
-- =============================================================================

CREATE TABLE public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES public.categories(id),
    title varchar(256) NOT NULL,
    description text,
    price_retail numeric(12,2) NOT NULL,
    price_wholesale numeric(12,2) NOT NULL,
    wholesale_threshold integer NOT NULL DEFAULT 10,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE public.product_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    size varchar(32) NOT NULL,
    color varchar(32) NOT NULL,
    weight numeric(8,2) NOT NULL,
    sku varchar(128) UNIQUE,
    is_active BOOLEAN DEFAULT true
);

CREATE INDEX idx_products_category_id ON public.products(category_id);

CREATE TABLE public.discounts (
    category_id bigint PRIMARY KEY REFERENCES public.categories(id),
    discount numeric(3,2) NOT NULL
);

-- =============================================================================
-- 3. СКЛАДСКОЙ УЧЕТ (STOCK)
-- =============================================================================

CREATE TABLE public.stock (
    variant_id bigint NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
    warehouse_id bigint NOT NULL REFERENCES public.warehouses(id),
    quantity bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (variant_id, warehouse_id)
);

-- =============================================================================
-- 4. ЗАКАЗЫ И КОРЗИНЫ
-- =============================================================================

CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id),
    warehouse_id bigint REFERENCES public.warehouses(id),
    price numeric(12,2) NOT NULL,
    address text NOT NULL,
    status varchar(32) NOT NULL,
    payment_method varchar(32) NOT NULL DEFAULT 'CASH',
    date timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_orders_user_id ON public.orders(user_id);
CREATE INDEX idx_orders_warehouse_id ON public.orders(warehouse_id);

CREATE TABLE public.order_items (
    order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    variant_id bigint NOT NULL REFERENCES public.product_variants(id),
    quantity bigint NOT NULL,
    price_at_purchase numeric(12,2) NOT NULL,
    total_price numeric(12,2) NOT NULL,
    comment TEXT,
    PRIMARY KEY (order_id, variant_id)
);

CREATE TABLE public.order_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    new_status varchar(32) NOT NULL,
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    changed_by bigint REFERENCES public.users(id),
    comment TEXT NOT NULL
);

CREATE TABLE public.carts (
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    variant_id bigint NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
    quantity bigint NOT NULL DEFAULT 1,
    PRIMARY KEY (user_id, variant_id)
);

-- =============================================================================
-- 5. ПРОФИЛИ И БЕЗОПАСНОСТЬ
-- =============================================================================

CREATE TABLE public.individual_details (
    user_id bigint PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    first_name varchar(256) NOT NULL,
    last_name varchar(256) NOT NULL,
    midname varchar(256),
    birthdate date NOT NULL,
    passport_series varchar(4) NOT NULL,
    passport_number varchar(6) NOT NULL
);

CREATE TABLE public.legal_details (
    user_id bigint PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    company_name varchar(256) NOT NULL,
    inn varchar(12) NOT NULL,
    kpp varchar(9),
    ogrn varchar(15) NOT NULL,
    legal_address varchar(256) NOT NULL
);

CREATE TABLE public.user_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    token text UNIQUE NOT NULL,
    expiry_date timestamp without time zone NOT NULL,
    revoked boolean NOT NULL DEFAULT false
);

CREATE INDEX idx_user_tokens_user_id ON public.user_tokens(user_id);

CREATE TABLE images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    product_variant_id BIGINT NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
    type VARCHAR(32) DEFAULT 'GALLERY',
    sort_order INT DEFAULT 0,     
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
