CREATE TYPE user_role AS ENUM ('INDIVIDUAL', 'LEGAL', 'MANAGER', 'ADMIN');
CREATE TYPE deliver_status AS ENUM ('PENDING', 'PAID', 'ASSEMBLED', 'SHIPPED', 'DELIVERED')

-- =============================================================================
-- 1. СПРАВОЧНИКИ (Таблицы, на которые все ссылаются)
-- =============================================================================

CREATE TABLE public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64) UNIQUE NOT NULL
);

CREATE TABLE public.warehouses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address text NOT NULL
);

CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(32) UNIQUE NOT NULL,
    password_hash text NOT NULL,
    role user_role NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 2. ТОВАРЫ И ЦЕНООБРАЗОВАНИЕ
-- =============================================================================

CREATE TABLE public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES public.categories(id),
    title varchar(256) NOT NULL,
    description text,
    weight numeric(8,2) NOT NULL, -- До 999999.99 (с запасом)
    size varchar(64) NOT NULL,
    price_retail numeric(12,2) NOT NULL,
    price_wholesome numeric(12,2) NOT NULL,
    wholesale_threshold integer NOT NULL DEFAULT 10
);

CREATE INDEX idx_products_category_id ON public.products(category_id);

CREATE TABLE public.discounts (
    category_id bigint PRIMARY KEY REFERENCES public.categories(id),
    discount numeric(3,2) NOT NULL -- Например, 0.15 для 15%
);

-- =============================================================================
-- 3. СКЛАДСКОЙ УЧЕТ (STOCK)
-- =============================================================================

CREATE TABLE public.stock (
    product_id bigint NOT NULL REFERENCES public.products(id),
    warehouse_id bigint NOT NULL REFERENCES public.warehouses(id),
    quantity bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (product_id, warehouse_id)
);

-- =============================================================================
-- 4. ЗАКАЗЫ И КОРЗИНЫ
-- =============================================================================

CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id),
    warehouse_id bigint NOT NULL REFERENCES public.warehouses(id),
    price numeric(12,2) NOT NULL,
    address text NOT NULL,
    status deliver_status NOT NULL,
    date timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_orders_user_id ON public.orders(user_id);
CREATE INDEX idx_orders_warehouse_id ON public.orders(warehouse_id);

CREATE TABLE public.order_items (
    order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES public.products(id),
    quantity bigint NOT NULL,
    price_at_purchase numeric(12,2) NOT NULL,
    total_price numeric(12,2) NOT NULL,
    PRIMARY KEY (order_id, product_id)
);

CREATE TABLE public.order_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    new_status deliver_status NOT NULL,
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    changed_by bigint NOT NULL REFERENCES public.users(id)
);

CREATE TABLE public.carts (
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES public.products(id),
    quantity bigint NOT NULL DEFAULT 1,
    PRIMARY KEY (user_id, product_id)
);

-- =============================================================================
-- 5. ПРОФИЛИ ПОЛЬЗОВАТЕЛЕЙ И БЕЗОПАСНОСТЬ
-- =============================================================================

CREATE TABLE public.individual_details (
    user_id bigint PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    name varchar(256) NOT NULL,
    surname varchar(256) NOT NULL,
    midname varchar(256),
    birthdate date NOT NULL,
    phone varchar(20) NOT NULL,
    email varchar(256) NOT NULL,
    passport_series varchar(4) NOT NULL,
    passport_number varchar(6) NOT NULL
);

CREATE TABLE public.legal_details (
    user_id bigint PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    company_name varchar(256) NOT NULL,
    inn varchar(12) NOT NULL,
    kpp varchar(9),
    ogrn varchar(15) NOT NULL,
    legal_address varchar(256) NOT NULL
);

CREATE TABLE public.user_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    token text UNIQUE NOT NULL,
    expiry_date timestamp without time zone NOT NULL,
    revoked boolean NOT NULL DEFAULT false
);

CREATE INDEX idx_user_tokens_user_id ON public.user_tokens(user_id);