spring.application.name=store

# Database Settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/store_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:iR90H9tV}

# Hibernate & Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html