spring.application.name=store

# Database Settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/store_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

# Hibernate & Flyway
spring.jpa.properties.hibernate.validator.apply_to_ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

application.security.jwt.secret-key=MzIzYjNjYTU1MjE1NWRmM2ZhMTZjOWRhZjIzODM1OTg3ZjRlZDQ1NTNlZjQ0MWFiYTZlYWY2YTlmZWUzNTFlYw==
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000